# Generated by Django 3.1.2 on 2021-05-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadingdate', models.CharField(max_length=13, null=True)),
                ('name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
