# Generated by Django 3.1.2 on 2021-05-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='fav',
            field=models.CharField(default='no', max_length=200, null=True),
        ),
    ]
